import "../../style/index.css";
import { Inter, Cinzel_Decorative } from "next/font/google";
const inter = Inter({
  subsets: ["latin"],
  weight: "400",
});
export const cinzel = Cinzel_Decorative({
  subsets: ["latin"],
  weight: "700",
});
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' data-theme='dracula'>
      <body className={`${inter.className} flex  justify-center w-full `}>
        <main className=' max-w-[1600px] mx-auto w-full'>{children}</main>
      </body>
    </html>
  );
}
